<?php

namespace App\Http\Controllers;

use App\Models\BukuBesar;
use App\Models\Rekening;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;

class JurnalController extends Controller
{
    public function create()
    {
        return view('jurnal.create');
    }

    public function searchRekening(Request $request)
    {
        $koder = $request->query('koder');
        $rekening = Rekening::where('KODER', $koder)->first();

        if ($rekening) {
            return response()->json([
                'status' => 'found',
                'nama' => $rekening->NAMA
            ]);
        } else {
            return response()->json([
                'status' => 'not_found'
            ]);
        }
    }

    public function store(Request $request)
    {
        $request->validate([
            'cart' => 'required|array|min:1',
            'cart.*.tgl' => 'required|date',
            'cart.*.koder' => 'required|exists:gl_rekening,KODER',
            'cart.*.dk' => 'required|in:D,K',
            'cart.*.nominal' => 'required|numeric|min:1',
            'cart.*.ket' => 'required|string',
        ]);

        $cart = $request->cart;

        // 1. Validasi Balance
        $totalDebit = 0;
        $totalKredit = 0;

        foreach ($cart as $item) {
            if ($item['dk'] == 'D') {
                $totalDebit += $item['nominal'];
            } else {
                $totalKredit += $item['nominal'];
            }
        }

        if ($totalDebit != $totalKredit) {
            return back()->with('error', 'Jurnal tidak seimbang (Balance). Total Debit: ' . number_format($totalDebit) . ', Total Kredit: ' . number_format($totalKredit));
        }

        try {
            DB::transaction(function () use ($cart) {
                // 2. Generate No Slip uses System Date (Now)
                // NOSLIP Format: JR-YYYYMMDD-XXX
                $today = now();
                $dateCode = $today->format('Ymd');

                // Count transaction created TODAY for running number
                // We use created_at to count daily transactions generated by system
                $count = BukuBesar::whereDate('created_at', $today->toDateString())->count() + 1;
                $noSlip = 'JR-' . $dateCode . '-' . str_pad($count, 3, '0', STR_PAD_LEFT);

                foreach ($cart as $item) {
                    // Lock Rekening row
                    $rekening = Rekening::where('KODER', $item['koder'])->lockForUpdate()->first();

                    $debit = ($item['dk'] == 'D') ? $item['nominal'] : 0;
                    $kredit = ($item['dk'] == 'K') ? $item['nominal'] : 0;

                    // Hitung Saldo Baru
                    if ($rekening->A_P == 'A') {
                        $saldoBaru = $rekening->SALDO + $debit - $kredit;
                    } else {
                        $saldoBaru = $rekening->SALDO + $kredit - $debit;
                    }

                    // Insert Buku Besar
                    BukuBesar::create([
                        'TGL' => $item['tgl'], // Per-line date input
                        'TGLVAL' => $item['tgl'],
                        'NOSLIP' => $noSlip,
                        'KODER' => $item['koder'],
                        'DK' => $item['dk'],
                        'KET' => $item['ket'],
                        'SALDOAWAL' => $rekening->SALDO,
                        'DEBIT' => $debit,
                        'KREDIT' => $kredit,
                        'SALDO' => $saldoBaru,
                        'OPER' => Auth::user()->name,
                        'UNIT' => 'PUSAT'
                    ]);

                    // Update Master Rekening
                    $rekening->update([
                        'SALDO' => $saldoBaru,
                        'TGL' => now() // Last updated time
                    ]);
                }
            });

            return redirect()->route('jurnal.create')->with('success', 'Jurnal berhasil diposting!');
        } catch (\Exception $e) {
            return back()->with('error', 'Terjadi kesalahan sistem: ' . $e->getMessage());
        }
    }
}
