<?php

namespace App\Http\Controllers;

use App\Models\BukuBesar;
use App\Models\Rekening;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;

class JurnalController extends Controller
{
    public function create()
    {
        return view('jurnal.create');
    }

    public function searchRekening(Request $request)
    {
        $koder = $request->query('koder');
        $rekening = Rekening::where('KODER', $koder)->whereNot('TIPE', 'H')->first();

        if ($rekening) {
            return response()->json([
                'status' => 'found',
                'nama' => $rekening->NAMA
            ]);
        } else {
            return response()->json([
                'status' => 'not_found'
            ]);
        }
    }

    public function store(Request $request)
    {
        $request->validate([
            'cart' => 'required|array|min:1',
            'cart.*.tgl' => 'required|date',
            'cart.*.koder' => 'required|exists:gl_rekening,KODER',
            'cart.*.dk' => 'required|in:D,K',
            'cart.*.nominal' => 'required|numeric|min:1',
            'cart.*.ket' => 'required|string',
        ]);

        $cart = $request->cart;

        // 1. Validasi Balance
        $totalDebit = 0;
        $totalKredit = 0;

        foreach ($cart as $item) {
            if ($item['dk'] == 'D') {
                $totalDebit += $item['nominal'];
            } else {
                $totalKredit += $item['nominal'];
            }
        }

        if ($totalDebit != $totalKredit) {
            return back()->with('error', 'Jurnal tidak seimbang (Balance). Total Debit: ' . number_format($totalDebit) . ', Total Kredit: ' . number_format($totalKredit));
        }

        try {
            DB::transaction(function () use ($cart) {
                // 2. Generate No Slip uses System Date (Now)
                // NOSLIP Format: JR-YYYYMMDD-XXX
                $today = now();
                $dateCode = $today->format('Ymd');

                // Count transaction created TODAY for running number
                // We use created_at to count daily transactions generated by system
                $count = BukuBesar::whereDate('created_at', $today->toDateString())->count() + 1;
                $noSlip = 'JR-' . $dateCode . '-' . str_pad($count, 3, '0', STR_PAD_LEFT);

                foreach ($cart as $item) {
                    // Lock Rekening row
                    $rekening = Rekening::where('KODER', $item['koder'])->lockForUpdate()->first();

                    $debit = ($item['dk'] == 'D') ? $item['nominal'] : 0;
                    $kredit = ($item['dk'] == 'K') ? $item['nominal'] : 0;

                    // Hitung Saldo Baru
                    if (in_array($rekening->A_P, ['A', 'O'])) {
                        // Debit increases Asset (A) and Expense (O)
                        $saldoBaru = $rekening->SALDO + $debit - $kredit;
                    } else {
                        // Credit increases Liability/Equity (P) and Revenue (L)
                        $saldoBaru = $rekening->SALDO + $kredit - $debit;
                    }

                    // Insert Buku Besar
                    BukuBesar::create([
                        'TGL' => $item['tgl'], // Per-line date input
                        'TGLVAL' => $item['tgl'],
                        'NOSLIP' => $noSlip,
                        'KODER' => $item['koder'],
                        'DK' => $item['dk'],
                        'KET' => $item['ket'],
                        'SALDOAWAL' => $rekening->SALDO,
                        'DEBIT' => $debit,
                        'KREDIT' => $kredit,
                        'SALDO' => $saldoBaru,
                        'OPER' => Auth::user()->name,
                        'UNIT' => 'PUSAT'
                    ]);

                    // Update Master Rekening
                    $rekening->update([
                        'SALDO' => $saldoBaru,
                        'TGL' => now() // Last updated time
                    ]);
                }

                // Batch Update Parent Balances
                // We do this AFTER the main loop to optimize locking if multiple lines touch the same parent
                // However, detailed simple approach: update inside the loop is safer for direct row locking.
                // Let's stick to update inside loop as per plan to ensure consistency per line.
                // Wait, if 2 lines touch same parent, we might deadlock if not careful.
                // But since we are in 1 DB transaction, and user is single operator likely, it's fine.
                // Better approach: Calculate total delta for each unique parent and update once?
                // For simplicity and robustness as per plan: Update immediately.
            });

            // Move the loop content back here to ensure scope access
            /* 
                Actually, the plan said: 
                "Inside store method, call updateParentBalances after updating the transaction account."
              */

            DB::transaction(function () use ($cart) {
                // 2. Generate No Slip uses System Date (Now)
                // NOSLIP Format: JR-YYYYMMDD-XXX
                $today = now();
                $dateCode = $today->format('Ymd');

                // Count transaction created TODAY for running number
                // We use created_at to count daily transactions generated by system
                $count = BukuBesar::whereDate('created_at', $today->toDateString())->count() + 1;
                $noSlip = 'JR-' . $dateCode . '-' . str_pad($count, 3, '0', STR_PAD_LEFT);

                foreach ($cart as $item) {
                    // Lock Rekening row
                    $rekening = Rekening::where('KODER', $item['koder'])->lockForUpdate()->first();

                    $debit = ($item['dk'] == 'D') ? $item['nominal'] : 0;
                    $kredit = ($item['dk'] == 'K') ? $item['nominal'] : 0;

                    // Hitung Saldo Baru
                    if (in_array($rekening->A_P, ['A', 'O'])) {
                        // Debit increases Asset (A) and Expense (O)
                        $saldoBaru = $rekening->SALDO + $debit - $kredit;
                    } else {
                        // Credit increases Liability/Equity (P) and Revenue (L)
                        $saldoBaru = $rekening->SALDO + $kredit - $debit;
                    }

                    // Insert Buku Besar
                    BukuBesar::create([
                        'TGL' => $item['tgl'], // Per-line date input
                        'TGLVAL' => $item['tgl'],
                        'NOSLIP' => $noSlip,
                        'KODER' => $item['koder'],
                        'DK' => $item['dk'],
                        'KET' => $item['ket'],
                        'SALDOAWAL' => $rekening->SALDO,
                        'DEBIT' => $debit,
                        'KREDIT' => $kredit,
                        'SALDO' => $saldoBaru,
                        'OPER' => Auth::user()->name,
                        'UNIT' => 'PUSAT'
                    ]);

                    // Update Master Rekening
                    $rekening->update([
                        'SALDO' => $saldoBaru,
                        'TGL' => now() // Last updated time
                    ]);

                    // UPDATE PARENT BALANCES
                    $this->updateParentBalances($item['koder'], $debit, $kredit, $rekening->A_P);
                }
            });

            return redirect()->route('jurnal.create')->with('success', 'Jurnal berhasil disimpan!');
        } catch (\Exception $e) {
            Log::error($e->getMessage());
            return back()->with('error', 'Terjadi kesalahan sistem');
        }
    }

    private function updateParentBalances($koder, $debit, $kredit, $rekeningAP)
    {
        // 1. Identify Parent (Level 2: X-XX000)
        // Example: 1-10001 -> 1-10000
        $parentCode = substr($koder, 0, 1) . '-' . substr($koder, 2, 2) . '000';

        // 2. Identify Grandparent (Level 1: X-00000)
        // Example: 1-10001 -> 1-00000
        $grandParentCode = substr($koder, 0, 1) . '-00000';

        // Check if Parent exists and is different from child
        if ($parentCode !== $koder) {
            $parent = Rekening::where('KODER', $parentCode)->first();
            if ($parent) {
                // Determine addition/subtraction based on A_P group
                // Although parents usually have same Group as child, we should use the Parent's specific group or the Child's passed group? 
                // Usually same hierarchy share same Normal Balance. Let's assume passed $rekeningAP is consistent for the whole tree.
                // Or better, fetch parent's A_P to be sure.

                if (in_array($parent->A_P, ['A', 'O'])) {
                    $newSaldo = $parent->SALDO + $debit - $kredit;
                } else {
                    $newSaldo = $parent->SALDO + $kredit - $debit;
                }

                $parent->update(['SALDO' => $newSaldo]);
            }
        }

        // Check if Grandparent exists and is different from child/parent
        if ($grandParentCode !== $parentCode && $grandParentCode !== $koder) {
            $grandParent = Rekening::where('KODER', $grandParentCode)->first();
            if ($grandParent) {
                if (in_array($grandParent->A_P, ['A', 'O'])) {
                    $newSaldo = $grandParent->SALDO + $debit - $kredit;
                } else {
                    $newSaldo = $grandParent->SALDO + $kredit - $debit;
                }

                $grandParent->update(['SALDO' => $newSaldo]);
            }
        }
    }

    public function syncBalances()
    {
        try {
            DB::transaction(function () {
                // 1. Reset SALDO of all Header (Induk) accounts to 0
                Rekening::where('TIPE', 'H')->update(['SALDO' => 0]);

                // 2. Fetch all Detail (Transaksi) accounts with non-zero balance
                $details = Rekening::where('TIPE', 'D')->where('SALDO', '!=', 0)->get();

                foreach ($details as $detail) {
                    $koder = $detail->KODER;
                    $saldo = $detail->SALDO;

                    // Parent
                    $parentCode = substr($koder, 0, 1) . '-' . substr($koder, 2, 2) . '000';
                    if ($parentCode !== $koder) {
                        $parent = Rekening::where('KODER', $parentCode)->first();
                        if ($parent) {
                            $parent->SALDO += $saldo;
                            $parent->save();
                        }
                    }

                    // Grandparent
                    $grandParentCode = substr($koder, 0, 1) . '-00000';
                    if ($grandParentCode !== $parentCode && $grandParentCode !== $koder) {
                        $grandParent = Rekening::where('KODER', $grandParentCode)->first();
                        if ($grandParent) {
                            $grandParent->SALDO += $saldo;
                            $grandParent->save();
                        }
                    }
                }
            });

            return back()->with('success', 'Saldo rekening induk berhasil disinkronisasi ulang!');
        } catch (\Exception $e) {
            Log::error($e->getMessage());
            return back()->with('error', 'Gagal menyinkronkan saldo: ' . $e->getMessage());
        }
    }
}
